### ISSUE TITLE
FR #12: Untestable

### ISSUE THREAD

**Issue by kkevlar** [matthewlewis112/Santa-He-knows-when-your-asleep-#40]
FR #12 reads:

> The system shall allow the user to delay for a designated time when to interact with devices after user falls asleep.

This requirement is untestable because it lacks clarity as to how much time the system should delay before interacting with its connected.
* Can the user tell the system to delay for a specified period of time (say, maybe 10 minutes?)
* Can the user define how long the delay should be? If so, is there a limit on how long the user can choose to delay the interaction?

**Comment by matthewlewis112** [comment]
Comment for the group: Should we let the user specify time delays?

**Comment by Elewis97** [comment]
We decided to not include time delays. We instead made a new functional requirement
